apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "authentication.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "authentication.name" . }}
    helm.sh/chart: {{ include "authentication.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "authentication.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "authentication.name" . }}
        app.domain: rplan
        app.kubernetes.io/name: {{ include "authentication.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: authentication__public-key
            valueFrom:
              secretKeyRef:
                name: {{ include "authentication.fullname" . }}-secrets
                key: public_key
          - name: authentication__private-key
            valueFrom:
              secretKeyRef:
                name: {{ include "authentication.fullname" . }}-secrets
                key: private_key
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /public-key
              port: http
          readinessProbe:
            httpGet:
              path: /public-key
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
