apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authentication.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "authentication.name" . }}
    helm.sh/chart: {{ include "authentication.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  private_key: {{ .Values.secrets.private_key }}
  public_key: {{ .Values.secrets.public_key }}
