{{- if .Values.ingress.enabled -}}
{{- $fullName := include "ingress.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "ingress.name" . }}
    helm.sh/chart: {{ include "ingress.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.authHost}}
      http:
        paths:
          - backend:
              serviceName: authentication
              servicePort: 8081
    - host:  {{ .Values.ingress.treeHost}}
      http:
        paths:
          - backend:
              serviceName: tree-service
              servicePort: 8082
    - host:  {{ .Values.ingress.prometheusHost}}
      http:
        paths:
          - backend:
              serviceName: monitoring-prometheus-server
              servicePort: 9090
    - host:  {{ .Values.ingress.kibanaHost}}
      http:
        paths:
          - backend:
              serviceName: monitoring-kibana
              servicePort: 5601
{{- end }}
