apiVersion: v1
kind: Service
metadata:
  name: {{ include "couchbase.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "couchbase.name" . }}
    helm.sh/chart: {{ include "couchbase.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP
      name: couchbase
  selector:
    app.kubernetes.io/name: {{ include "couchbase.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
